# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg_from',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msg_to',
        ),
    ]
