# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170620_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_to',
            field=models.IntegerField(default=0),
        ),
    ]
